//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellSmartPhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoHanh
    {
        public int Mabaohanh { get; set; }
        public Nullable<int> MaSp { get; set; }
        public string thoigianbaohanh { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> Ngayhetbaohanh { get; set; }
    
        public virtual ChitietDH ChitietDH { get; set; }
    }
}
