//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellSmartPhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietDH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChitietDH()
        {
            this.BaoHanhs = new HashSet<BaoHanh>();
        }
    
        public int MaChitietDH { get; set; }
        public Nullable<int> MaDH { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> Thanhtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoHanh> BaoHanhs { get; set; }
        public virtual DonhangKH DonhangKH { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
