//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellSmartPhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonhangKH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonhangKH()
        {
            this.ChitietDHs = new HashSet<ChitietDH>();
        }
    
        public int MaDH { get; set; }
        public int MaKH { get; set; }
        public Nullable<double> Phivanchuyen { get; set; }
        public string PhuongthucTT { get; set; }
        public System.DateTime Ngaydatmua { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> Tinhtrangdonhang { get; set; }
        public string ghichu { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietDH> ChitietDHs { get; set; }
    }
}
