//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellSmartPhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khuyenmai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khuyenmai()
        {
            this.SPkhuyenmais = new HashSet<SPkhuyenmai>();
        }
    
        public int MaKM { get; set; }
        public System.DateTime Ngaybatdau { get; set; }
        public System.DateTime Ngayketthuc { get; set; }
        public string noidung { get; set; }
        public string ten { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPkhuyenmai> SPkhuyenmais { get; set; }
    }
}
