//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellSmartPhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.Binhluans = new HashSet<Binhluan>();
            this.ChitietDHs = new HashSet<ChitietDH>();
            this.Hopdongs = new HashSet<Hopdong>();
            this.SPkhuyenmais = new HashSet<SPkhuyenmai>();
            this.Thongsokythuats = new HashSet<Thongsokythuat>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public int LoaiSP { get; set; }
        public int HangSX { get; set; }
        public string Xuatxu { get; set; }
        public double Gia { get; set; }
        public string Mota { get; set; }
        public string Anh { get; set; }
        public Nullable<int> Isnew { get; set; }
        public Nullable<int> Ishot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Binhluan> Binhluans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietDH> ChitietDHs { get; set; }
        public virtual HangSX HangSX1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hopdong> Hopdongs { get; set; }
        public virtual LoaiSP LoaiSP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPkhuyenmai> SPkhuyenmais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thongsokythuat> Thongsokythuats { get; set; }
    }
}
