//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellSmartPhone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SellphonesEntities : DbContext
    {
        public SellphonesEntities()
            : base("name=SellphonesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<BaoHanh> BaoHanhs { get; set; }
        public virtual DbSet<Binhluan> Binhluans { get; set; }
        public virtual DbSet<ChitietDH> ChitietDHs { get; set; }
        public virtual DbSet<DonhangKH> DonhangKHs { get; set; }
        public virtual DbSet<HangSX> HangSXes { get; set; }
        public virtual DbSet<Hopdong> Hopdongs { get; set; }
        public virtual DbSet<Khuyenmai> Khuyenmais { get; set; }
        public virtual DbSet<LoaiSP> LoaiSPs { get; set; }
        public virtual DbSet<Nhacungcap> Nhacungcaps { get; set; }
        public virtual DbSet<Sanpham> Sanphams { get; set; }
        public virtual DbSet<SPkhuyenmai> SPkhuyenmais { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Thongsokythuat> Thongsokythuats { get; set; }
    
        public virtual int addproduct(Nullable<int> maSP, string tenSP, Nullable<int> loaiSP, Nullable<int> hangSX, string xuatxu, Nullable<double> gia, string mota, string anh, Nullable<int> isnew, Nullable<int> ishot)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var loaiSPParameter = loaiSP.HasValue ?
                new ObjectParameter("LoaiSP", loaiSP) :
                new ObjectParameter("LoaiSP", typeof(int));
    
            var hangSXParameter = hangSX.HasValue ?
                new ObjectParameter("HangSX", hangSX) :
                new ObjectParameter("HangSX", typeof(int));
    
            var xuatxuParameter = xuatxu != null ?
                new ObjectParameter("Xuatxu", xuatxu) :
                new ObjectParameter("Xuatxu", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(double));
    
            var motaParameter = mota != null ?
                new ObjectParameter("Mota", mota) :
                new ObjectParameter("Mota", typeof(string));
    
            var anhParameter = anh != null ?
                new ObjectParameter("Anh", anh) :
                new ObjectParameter("Anh", typeof(string));
    
            var isnewParameter = isnew.HasValue ?
                new ObjectParameter("Isnew", isnew) :
                new ObjectParameter("Isnew", typeof(int));
    
            var ishotParameter = ishot.HasValue ?
                new ObjectParameter("Ishot", ishot) :
                new ObjectParameter("Ishot", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addproduct", maSPParameter, tenSPParameter, loaiSPParameter, hangSXParameter, xuatxuParameter, giaParameter, motaParameter, anhParameter, isnewParameter, ishotParameter);
        }
    
        public virtual int addthongsokythuat(Nullable<int> maSP, string thuoctinh, string giatri)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var thuoctinhParameter = thuoctinh != null ?
                new ObjectParameter("Thuoctinh", thuoctinh) :
                new ObjectParameter("Thuoctinh", typeof(string));
    
            var giatriParameter = giatri != null ?
                new ObjectParameter("Giatri", giatri) :
                new ObjectParameter("Giatri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addthongsokythuat", maSPParameter, thuoctinhParameter, giatriParameter);
        }
    
        public virtual ObjectResult<get_product_discount_Result> get_product_discount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_product_discount_Result>("get_product_discount");
        }
    
        public virtual int add_comment(Nullable<int> maBL, Nullable<int> maSP, Nullable<int> maKH, string noidung, Nullable<System.DateTime> date, string hoten, string email)
        {
            var maBLParameter = maBL.HasValue ?
                new ObjectParameter("MaBL", maBL) :
                new ObjectParameter("MaBL", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("Noidung", noidung) :
                new ObjectParameter("Noidung", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_comment", maBLParameter, maSPParameter, maKHParameter, noidungParameter, dateParameter, hotenParameter, emailParameter);
        }
    
        public virtual ObjectResult<get_comment_Result> get_comment(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_comment_Result>("get_comment", maSPParameter);
        }
    
        public virtual int edit_password(Nullable<int> idaccount, string password)
        {
            var idaccountParameter = idaccount.HasValue ?
                new ObjectParameter("idaccount", idaccount) :
                new ObjectParameter("idaccount", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("edit_password", idaccountParameter, passwordParameter);
        }
    
        public virtual int update_account(Nullable<int> idaccount, string email, string phone, string hoten, Nullable<System.DateTime> ngaysinh, string diachi)
        {
            var idaccountParameter = idaccount.HasValue ?
                new ObjectParameter("idaccount", idaccount) :
                new ObjectParameter("idaccount", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_account", idaccountParameter, emailParameter, phoneParameter, hotenParameter, ngaysinhParameter, diachiParameter);
        }
    
        public virtual ObjectResult<Load_Cart_Result> Load_Cart(Nullable<int> idKH)
        {
            var idKHParameter = idKH.HasValue ?
                new ObjectParameter("idKH", idKH) :
                new ObjectParameter("idKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Load_Cart_Result>("Load_Cart", idKHParameter);
        }
    }
}
