//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellSmartPhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thongsokythuat
    {
        public int MaSP { get; set; }
        public string Thuoctinh { get; set; }
        public string Giatri { get; set; }
    
        public virtual Sanpham Sanpham { get; set; }
    }
}
